/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2019-10-16 12:02:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import LF.seller.model.vo.*;

public final class SellerInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("LF.seller.model.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

/*	Seller s = (Seller)request.getAttribute("seller"); 
	//로그인 된 정보에서 Seller 계정 가져오기

 	String bName = s.getbName();
	String bNum = s.getbNum();
	String cpNum = s.getCpNum();
	
	//물품판매 권한 승인 여부에 따라 문구가 달라야 함
	String bStatus = s.getbStatus() != 'Y' ? "판매 권한 검토중입니다" : "승인 완료";
	
	String bankName = s.getBankName();
	String acNum = s.getAcName();
	String acName = s.getAcName();
	int fId = s.getfId();	//사업자 등록증 봐야 할 거 같다고 생각되면 파일 불러오는거 구현해야 함  */
	
	Seller s = new Seller();
	
	String bName = "사업자명";
	String bNum = "사업자번호";
	String cpNum = "법인번호";
	String bStatus = s.getbStatus() != 'Y' ? "판매 권한 검토중입니다" : "승인 완료";
	
	String bankName = "은행명";
	String acNum = "계좌번호";
	String acName = "예금주";
	

      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- 사업자 인증이 완료된 경우에만 사업자 정보 확인 가능 -->\r\n");
      out.write("<!-- 사업자 정보 페이지는 사업자 등록정보만 확인 가능 -->\r\n");
      out.write("<!-- 전화번호, 이메일, 주소, 비밀번호, 비밀번호 확인 등의 계정 정보 수정은 마이페이지에서 수정 -->\r\n");
      out.write("<!-- 사업자 등록 진행상황(미신청, 대기, 완료), 사업자 등록번호, 판매승인여부,  -->\r\n");
      out.write("\t<h1>사업자 정보 확인</h1>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"SellerInfoArea\">\r\n");
      out.write("\t<!-- memberJoinForm.jsp에 있는 table을 복사해서 쓰자 -->\r\n");
      out.write("\r\n");
      out.write("\t\t<form id = \"bChange\" >\r\n");
      out.write("\t\t<table border:1px gray solid>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"150px\" align=\"left\">\t사업자명   </td>\r\n");
      out.write("\t\t\t\t<td> ");
      out.print(bName );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td><button id=\"bNameChange\" onclick=\"bPopup(this.form)\">사업자명 변경</button></td>\r\n");
      out.write("\t\t\t\t<td><input type=\"hidden\" id=\"bName\" name=\"bName\" value=\"");
      out.print(bName );
      out.write("\">\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"150px\">\t사업자 등록번호   </td>\r\n");
      out.write("\t\t\t\t<td> ");
      out.print(bNum );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t<td><input type=\"hidden\" value=\"");
      out.print(bNum );
      out.write("\">\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"150px\">\t법인 번호   </td>\r\n");
      out.write("\t\t\t\t<td> ");
      out.print(cpNum );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t<td><input type=\"hidden\" value=\"");
      out.print(cpNum );
      out.write("\">\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<table>\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"150px\">판매 권한 승인 여부   </td>\r\n");
      out.write("\t\t\t\t<td> ");
      out.print(bStatus );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t<td style=\"width:200px\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"150px\">\t입금계좌  </td>\r\n");
      out.write("\t\t\t\t<td> ");
      out.print(bankName );
      out.write(' ');
      out.write('/');
      out.write(' ');
      out.print(acNum );
      out.write(' ');
      out.print(acName );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t<td><button id=\"bankAccount\" onclick=\"acPopup();\">입금계좌 변경</button></td>\r\n");
      out.write("\t\t\t\t<td style=\"width:200px\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"150px\">사업자등록증 :  </td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(acName );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td style=\"width:200px\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<div class=\"btns\" align=\"center\">\r\n");
      out.write("\t\t\t\t<button id=\"goMain\" onclick=\"goMain();\">메인으로</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfunction goMain(){\r\n");
      out.write("\t\t\tlocation.href=\"/LimitedF/index.jsp\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction bPopup(bChange){\r\n");
      out.write("\t\t\t\r\n");
      out.write("            //var url=\"/testServlet\";\r\n");
      out.write("            var url = \"/LimitedF/views/bpopup.jsp\";\r\n");
      out.write("            var name = \"popup test\";\r\n");
      out.write("            var option = \"width = 500, height = 500, top = 100, left = 200, location = no\"\r\n");
      out.write("            window.open(url, name, option);\r\n");
      out.write("            /* \r\n");
      out.write("            bChange.action = \"testServlet\";\r\n");
      out.write("            bChange.target = name;\r\n");
      out.write("            bChange.method = \"post\";\r\n");
      out.write("            bChange.submit(); */\r\n");
      out.write("           \r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction acPopup(){\r\n");
      out.write("\t\t\tvar url = \"/LimitedF/views/acpopup.jsp\";\r\n");
      out.write("            var name = \"popup test\";\r\n");
      out.write("            var option = \"width = 500, height = 500, top = 100, left = 200, location = no\"\r\n");
      out.write("            window.open(url, name, option);\r\n");
      out.write("            \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t/* \r\n");
      out.write("\t\t$(\"#bNameChange\").click(function(){\r\n");
      out.write("\t\t\tvar bName = prompt(\"변경할 사업자명 입력 : \");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl:\"/LimitedF/bnc.do\",\t\t//SellerBNCServlet\r\n");
      out.write("\t\t\t\tdata:{bName:bname},\r\n");
      out.write("\t\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\twindow.alert(\"사업자명 변경 완료\");\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror:function(data){\r\n");
      out.write("\t\t\t\t\twindow.alert(\"에러\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}); \r\n");
      out.write("\t\t});*/\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
