/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2019-10-18 11:08:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.FAQ;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.*;

public final class Onebyone_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("* {\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=text], select, textarea {\r\n");
      out.write("  \r\n");
      out.write("  padding: 10px;\r\n");
      out.write("  border: 1px solid #ccc;\r\n");
      out.write("  border-radius: 6px;\r\n");
      out.write("  resize: vertical;\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("label {\r\n");
      out.write("  padding: 12px 12px 12px 0;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=submit] {\r\n");
      out.write("  background-color: #2a6fff;\r\n");
      out.write("  color: white;\r\n");
      out.write("  padding: 12px 20px;\r\n");
      out.write("  border: none;\r\n");
      out.write("  border-radius: 4px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  float: right;\r\n");
      out.write("  width : 100%;\r\n");
      out.write("  transition: 0.5s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=submit]:hover {\r\n");
      out.write("  background-color: #004dee;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("  background-color: #f2f2f2;\r\n");
      out.write("  padding: 20px;\r\n");
      out.write("  width : 750px;\r\n");
      out.write("  margin : 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".col-25 {\r\n");
      out.write(" \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".col-75 {\r\n");
      out.write("  float: left;\r\n");
      out.write("  width: 75%;\r\n");
      out.write("  margin-top: 6px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Clear floats after the columns */\r\n");
      out.write(".row:after {\r\n");
      out.write("  content: \"\";\r\n");
      out.write("  display: table;\r\n");
      out.write("  clear: both;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Responsive layout - when the screen is less than 600px wide, make the two columns stack on top of each other instead of next to each other */\r\n");
      out.write("@media screen and (max-width: 600px) {\r\n");
      out.write("  .col-25, .col-75, input[type=submit] {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    margin-top: 0;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn {\r\n");
      out.write("  background-color: DodgerBlue;\r\n");
      out.write("  border: none;\r\n");
      out.write("  color: white;\r\n");
      out.write("  padding: 12px 16px;\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  transition: 0.5s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn:hover {\r\n");
      out.write("  background-color: RoyalBlue;\r\n");
      out.write("}\r\n");
      out.write(".ImgPreview {\r\n");
      out.write("}\r\n");
      out.write(".ImgPreview img{\r\n");
      out.write("\t\r\n");
      out.write("\tmax-width : 190px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h1 align = \"center\">1:1문의</h1>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t<div class = \"container\">\r\n");
      out.write("\t\r\n");
      out.write("\t<table width =\"600px\" height=\"800px\" align = \"center\" >\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width = \"80px\">\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t아이디 \r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td width = \"380px\"> \t\r\n");
      out.write("\t\t\t\t <p>request.getId</p> \r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<select id = \"inquiryType\">\r\n");
      out.write("\t\t\t\t\t<option value = \"상품문의\">상품문의</option>\r\n");
      out.write("\t\t\t\t\t<option value = \"결제문의\">결제문의</option>\r\n");
      out.write("\t\t\t\t\t<option value = \"배송문의\">배송문의</option>\r\n");
      out.write("\t\t\t\t\t<option value = \"교환반품문의\">교환반품문의</option>\r\n");
      out.write("\t\t\t\t\t<option value = \"취소환불문의\">취소환불문의</option>\r\n");
      out.write("\t\t\t\t\t<option value = \"기타\">기타</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<label>E-MAIL</label>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td>\t\r\n");
      out.write("\t\t\t\t<input type = \"text\">\r\n");
      out.write("\t\t\t\t@ \r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"selfdomain\" id=\"selfdomain\" value=\"\" title=\"이메일 도메인 직접입력\" style=\"width: 120px; position: absolute; top: 15px;\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<select id =\"sampledomin\" name = \"domain\" style =\" vertical-align: middle;\">\r\n");
      out.write("\t\t\t\t\t\t<option value = \"\">선택</option>\r\n");
      out.write("\t\t\t\t\t\t<option value = \"naver.com\">naver.com</option>\r\n");
      out.write("\t\t\t\t\t\t<option value = \"gmail.com\">gmail.com</option>\r\n");
      out.write("\t\t\t\t\t\t<option value = \"daum.net\">daum.net</option>\r\n");
      out.write("\t\t\t\t\t\t<option value = \"hotmail.com\">hotmail.com</option>\r\n");
      out.write("\t\t\t\t\t\t<option value = \"empas.com\">empas.com</option>\r\n");
      out.write("\t\t\t\t\t\t<option value = \"yahoo.co.kr\">yahoo.co.kr</option>\r\n");
      out.write("\t\t\t\t\t\t<option value = \"nate.com\">nate.com</option>\r\n");
      out.write("\t\t\t\t\t\t<option value = \"self\">직접입력</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<input type = \"hidden\" id = \"putEmail\" name = \"putEmail\">\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<label>전화번호</label> \r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<select style = \"width : 70px\">\r\n");
      out.write("\t\t\t\t\t\t<option value = \"010\">010</option> \r\n");
      out.write("\t\t\t\t\t\t<option value = \"011\">011</option> \r\n");
      out.write("\t\t\t\t\t\t<option value = \"016\">016</option>\r\n");
      out.write("\t\t\t\t\t\t<option value = \"017\">017</option>\r\n");
      out.write("\t\t\t\t\t\t<option value = \"018\">018</option>\r\n");
      out.write("\t\t\t\t\t\t<option value = \"019\">019</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t-\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" style = \"width : 90px\" maxlength=\"4\">\r\n");
      out.write("\t\t\t\t\t-\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" style = \"width : 90px\" maxlength=\"4\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr >\r\n");
      out.write("\t\t   <td>\r\n");
      out.write("\t\t\t\t<label>제목</label>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td colspan = \"2\">\r\n");
      out.write("\t\t\t\t<input type =\"text\" style =\"width : 400px;\">\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<label>문의내용</label>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan =\"3\" align=\"center\"><textarea rows = \"20\" cols = \"80\" style = \"resize : none; width : 100%\"></textarea> </td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan =\"2\">\r\n");
      out.write("\t\t\t\t<button id = \"uploadicon\" class=\"btn\"><i class=\"fa fa-folder\"></i></button>\r\n");
      out.write("\t\t\t\t<input id = \"uploadroot\" type = \"file\" multiple =\"multiple\">\r\n");
      out.write("\t\t\t\t<p style = \"margin-top :0px; margin-bottom:0px;\" >이미지 미리보기</p>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<td colspan = \"3\" style =\"height: 120px;padding-left: 10px;padding-top: 6px; background : white; border-radius: 5px;\">\r\n");
      out.write("\t\t\t\t\t<div class = \"ImgPreview\" style =\" vertical-align: middle;\"> </div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<input type =\"submit\" value = \"보내기\">\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script> /*email 합치는 스크립트 */\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t$(function(){\r\n");
      out.write("\t\t     //직접입력 인풋박스 기존에는 숨어있다가\r\n");
      out.write("\t\t        $(\"#selfdomain\").hide();\r\n");
      out.write("\t\t        $(\"#sampledomin\").change(function() {\r\n");
      out.write("\t\t             //직접입력을 선택 시 나타남\r\n");
      out.write("\t\t             if($(\"#sampledomin\").val() == \"self\") {\r\n");
      out.write("\t\t             $(\"#selfdomain\").show();\r\n");
      out.write("\t\t             //이메일 조합\r\n");
      out.write("\t\t              var semail =  $('#emailId').val() + \"@\" + $('#selfdomail').val();\r\n");
      out.write("\t\t                $(\"#putEmail\").val(semail);\r\n");
      out.write("\t\t              }else{\r\n");
      out.write("\t\t                  $(\"#selfdomain\").val(\"\");\r\n");
      out.write("\t\t                  $(\"#selfdomain\").hide();\r\n");
      out.write("\t\t                  var semail = $('#emailId').val() + \"@\" + $('#sampledomin').val();\r\n");
      out.write("\t\t                  $(\"#putEmail\").val(semail);\r\n");
      out.write("\t\t                \t}\r\n");
      out.write("\t\t                 });\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script>  /*file upload 아이콘 input= type = file 으로 합치기*/\r\n");
      out.write("\t\t\t\t$('#uploadroot').hide();\t\r\n");
      out.write("\t\t\t\t\t$('#uploadicon').click(function(){\r\n");
      out.write("\t\t\t\t\t\t$('#uploadroot').click(); \r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<script>  /*미리보기 이미지 뿌려주는 스크립트*/\r\n");
      out.write("\t\t//이미지 정보들을 담을 배열\r\n");
      out.write("\t\t\tvar sel_files = [];\r\n");
      out.write("\r\n");
      out.write("\t\t\tindex = 0;\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\tcount = 0; \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(document).ready(function(){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$('#uploadroot').on(\"change\", handleImgFileSelect);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfunction fileUploadAction(){\r\n");
      out.write("\t\t\t\tconsole.log(\"fileUploadAction\");\r\n");
      out.write("\t\t\t\t$(\"#uploadroot\").trigger('click');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfunction handleImgFileSelect(e){\r\n");
      out.write("\t\t\t\tconsole.log(\"함수 실행 되는 타이밍\");\r\n");
      out.write("\t\t\t\t//이미지 정보들 초기화\r\n");
      out.write("\t\t\t\tsel_files = [];\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar files = e.target.files;\r\n");
      out.write("\t\t\t\tvar filesArr = Array.prototype.slice.call(files);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\tif(count < 3) {\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(filesArr.length <4){\r\n");
      out.write("\t\t\t\tfilesArr.forEach(function(f){\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tconsole.log(\"count=index에서  count:\" + count);\r\n");
      out.write("\t\t\t\t\tconsole.log(\"count=index에서  index:\" + index);\r\n");
      out.write("\t\t\t\t\tif(count<3){\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t//이미지 파일 아닌것 걸러내는 필터\r\n");
      out.write("\t\t\t\t\tif(!f.type.match(\"image.*\")){\r\n");
      out.write("\t\t\t\t\t\talert(\"이미지 파일만 업로드 가능합니다.\");\r\n");
      out.write("\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t//이미지 파일 f 를 sel files 배열에 push로 넣어주기\r\n");
      out.write("\t\t\t\t\tsel_files.push(f);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar reader = new FileReader();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\treader.onload = function(e){\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tvar html = \"<a href=\\\"javascript:void(0);\\\" onclick=\\\"deleteImageAction(\"\r\n");
      out.write("\t\t\t\t\t\t\t\t+index+\")\\\" id=\\\"img_id_\"+index+\"\\\" style =\\\"padding-left:1px;padding-right:1px;\\\"><img src=\\\"\"+e.target.result \r\n");
      out.write("\t\t\t\t\t\t\t\t+ \"\\\" data-file='\"+f.name+\"' class='selProductFile' title='클릭시 제거'></a>\";\r\n");
      out.write("\t\t\t\t\t\tindex++;\r\n");
      out.write("\t\t\t\t\t\t//ImgPreview div에 html 붙이고 인덱스 증가\r\n");
      out.write("\t\t\t\t\t\t$(\".ImgPreview\").append(html);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tcount++;\r\n");
      out.write("\t\t\t\t\tconsole.log(\"index : \" +index);\r\n");
      out.write("\t\t\t\t\tconsole.log(\"count : \" + count);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\treader.readAsDataURL(f);\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\talert(\"최대 세장까지 업로드 가능합니다.\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\talert(\"최대 세장까지 업로드 가능합니다.\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//클릭시 사진 제거하는 펑션\t\t\t\t\r\n");
      out.write("\t\t\tfunction deleteImageAction(index){\r\n");
      out.write("\t\t\t\tconsole.log(\"index : \" + index);\r\n");
      out.write("\t\t\t\tsel_files.splice(index,1);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar img_id = \"#img_id_\" + index;\r\n");
      out.write("\t\t\t\t$(img_id).remove();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tconsole.log(sel_files);\r\n");
      out.write("\t\t\t\tcount--;\r\n");
      out.write("\t\t\t\tconsole.log(\"지울 떄 : \" + count);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
