/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2019-10-24 16:03:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import board.model.vo.*;
import java.util.*;

public final class Payment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("board.model.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");

	Board buyList = (Board)request.getAttribute("board");
	int mCount = (Integer)request.getAttribute("mCount");
	String pathImg = (String)request.getAttribute("pathImg");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>결제 페이지</title>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\t.info{\r\n");
      out.write("\t\tborder: 1px solid;\r\n");
      out.write("\t\tborder-color: #ddd #ddd #CACACA;\r\n");
      out.write("\t\twidth: 1000px;\r\n");
      out.write("    \theight: 360px;\r\n");
      out.write("    \tmargin-left:auto;\r\n");
      out.write("        margin-right:auto;\r\n");
      out.write("        margin-top:50px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.PList{\r\n");
      out.write("\t\tborder: 1px solid;\r\n");
      out.write("\t\tborder-color: #ddd #ddd #CACACA;\r\n");
      out.write("\t\twidth: 1000px;\r\n");
      out.write("    \theight: 360px;\r\n");
      out.write("    \tmargin-left:auto;\r\n");
      out.write("        margin-right:auto;\r\n");
      out.write("        margin-top:10px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.infotable{\r\n");
      out.write("\t\tborder: 1px solid;\r\n");
      out.write("\t\tborder-color: #ddd #ddd #CACACA;\r\n");
      out.write("\t\twidth: 900px;\r\n");
      out.write("    \theight: 300px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.thmo{\r\n");
      out.write("\t\twidth: 110px; \r\n");
      out.write("\t\theight: 50px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.pay{\r\n");
      out.write("\t\tborder: 1px solid;\r\n");
      out.write("\t\tborder-color: #ddd #ddd #CACACA;\r\n");
      out.write("\t\twidth: 1000px;\r\n");
      out.write("    \theight: 100%;\r\n");
      out.write("    \tmargin-left:auto;\r\n");
      out.write("        margin-right:auto;\r\n");
      out.write("        margin-top:5px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#payinfo1{\r\n");
      out.write("\t\tdisplay:inline;\r\n");
      out.write("\t\tfloat:left;\r\n");
      out.write("\t\twidth: 500px;\r\n");
      out.write("    \theight: 400px;\r\n");
      out.write("    \tmargin-left:auto;\r\n");
      out.write("        margin-right:auto;\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\t#payinfo2{\r\n");
      out.write("\t\tdisplay:inline;\r\n");
      out.write("\t\tfloat:left;\r\n");
      out.write("\t\twidth: 500px;\r\n");
      out.write("    \theight: 400px;\r\n");
      out.write("    \tmargin-left:auto;\r\n");
      out.write("        margin-right:auto;\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\t.payui1{\r\n");
      out.write("\tborder: 1px solid;\r\n");
      out.write("\t\twidth: 460px; \r\n");
      out.write("\t\theight: 100px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.payui2{\r\n");
      out.write("\t\twidth: 460px; \r\n");
      out.write("\t\theight: 250px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.payui3{\r\n");
      out.write("\t\twidth: 460px; \r\n");
      out.write("\t\theight: 150px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#aaa:visited{\r\n");
      out.write("\t\tbackground: red;\r\n");
      out.write("\t\tcolor: green;\r\n");
      out.write("\t}\r\n");
      out.write("\t#bbb:visited{\r\n");
      out.write("\t\tbackground-color: red;\r\n");
      out.write("\t}\r\n");
      out.write("\t#ccc:visited{\r\n");
      out.write("\t\tbackground: red;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("    function sample6_execDaumPostcode() {\r\n");
      out.write("        new daum.Postcode({\r\n");
      out.write("            oncomplete: function(data) {\r\n");
      out.write("                // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("\r\n");
      out.write("                // 각 주소의 노출 규칙에 따라 주소를 조합한다.\r\n");
      out.write("                // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("                var addr = ''; // 주소 변수\r\n");
      out.write("                var extraAddr = ''; // 참고항목 변수\r\n");
      out.write("\r\n");
      out.write("                //사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.\r\n");
      out.write("                if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우\r\n");
      out.write("                    addr = data.roadAddress;\r\n");
      out.write("                } else { // 사용자가 지번 주소를 선택했을 경우(J)\r\n");
      out.write("                    addr = data.jibunAddress;\r\n");
      out.write("                }\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("                // 사용자가 선택한 주소가 도로명 타입일때 참고항목을 조합한다.\r\n");
      out.write("                if(data.userSelectedType === 'R'){\r\n");
      out.write("                    // 법정동명이 있을 경우 추가한다. (법정리는 제외)\r\n");
      out.write("                    // 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\r\n");
      out.write("                    if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){\r\n");
      out.write("                        extraAddr += data.bname;\r\n");
      out.write("                    }\r\n");
      out.write("                    // 건물명이 있고, 공동주택일 경우 추가한다.\r\n");
      out.write("                    if(data.buildingName !== '' && data.apartment === 'Y'){\r\n");
      out.write("                        extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);\r\n");
      out.write("                    }\r\n");
      out.write("                    // 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.\r\n");
      out.write("                    if(extraAddr !== ''){\r\n");
      out.write("                        extraAddr = ' (' + extraAddr + ')';\r\n");
      out.write("                    }\r\n");
      out.write("                    // 조합된 참고항목을 해당 필드에 넣는다.\r\n");
      out.write("                    document.getElementById(\"sample6_extraAddress\").value = extraAddr;\r\n");
      out.write("                \r\n");
      out.write("                } else {\r\n");
      out.write("                    document.getElementById(\"sample6_extraAddress\").value = '';\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                // 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("                document.getElementById(\"sample6_address\").value = addr;\r\n");
      out.write("                // 커서를 상세주소 필드로 이동한다.\r\n");
      out.write("                document.getElementById(\"sample6_detailAddress\").focus();\r\n");
      out.write("            }\r\n");
      out.write("        }).open();\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tfunction paygo(){\r\n");
      out.write("\t\t\tvar name = document.getElementById(\"name\").value;\r\n");
      out.write("\t\t\tvar phone2 = document.getElementById(\"phone2\").value;\r\n");
      out.write("\t\t\tvar phone3 = document.getElementById(\"phone3\").value;\r\n");
      out.write("\t\t\tvar add1 = document.getElementById(\"sample6_address\").value;\r\n");
      out.write("\t\t\tvar add2 = document.getElementById(\"sample6_detailAddress\").value;\r\n");
      out.write("\t\t\tvar add3 = document.getElementById(\"sample6_extraAddress\").value;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(name == \"\" || phone2 == \"\" || phone3 == \"\" || add1 == \"\" || add2 == \"\"){\r\n");
      out.write("\t\t\t\talert(\"배송 정보를 모두 기입해주세요!\");\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t    window.name = \"Payment\";\r\n");
      out.write("\t\t    // window.open(\"open할 window\", \"자식창 이름\", \"팝업창 옵션\");\r\n");
      out.write("\t\t    openWin = window.open(\"view/PaymentA.jsp\",\r\n");
      out.write("\t\t            \"PaymentA\", \"width=850, height=700, resizable = no, scrollbars = no\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t\tfunction onlyNumber(event){\r\n");
      out.write("\t\t\tevent = event || window.event;\r\n");
      out.write("\t\t\tvar keyID = (event.which) ? event.which : event.keyCode;\r\n");
      out.write("\t\t\tif ( (keyID >= 48 && keyID <= 57) || (keyID >= 96 && keyID <= 105) || keyID == 8 || keyID == 46 || keyID == 37 || keyID == 39 ) \r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction removeChar(event) {\r\n");
      out.write("\t\t\tevent = event || window.event;\r\n");
      out.write("\t\t\tvar keyID = (event.which) ? event.which : event.keyCode;\r\n");
      out.write("\t\t\tif ( keyID == 8 || keyID == 46 || keyID == 37 || keyID == 39 ) \r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t\tevent.target.value = event.target.value.replace(/[^0-9]/g, \"\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<form>\r\n");
      out.write("\t\t\t<div class=\"info\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"pid\" name=\"pid\" value=\"");
      out.print(buyList.getpId() );
      out.write("\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"sid\" name=\"sid\" value=\"");
      out.print(buyList.getsId() );
      out.write("\">\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"mCount\" name=\"mCount\" value=\"");
      out.print(mCount);
      out.write("\">\r\n");
      out.write("\t\t\t\t<font  color=\"#5D5D5D\" size=\"5\" style=\"margin-left: 5%; font-weight:300;\">배송 정보</font>\r\n");
      out.write("\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t<table class=\"infotable\" style=\"margin-left: 5%; margin-right:5%;\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"thmo\">이름</th>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" id=\"name\" size=\"20\" name=\"name\" maxlength=\"20\"></td>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"thmo\">연락처</th>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<select id=\"phone1\" style=\"width:66px;height:21.33px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"010\">010</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"011\">011</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"016\">016</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"017\">017</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"019\">019</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t- <input id=\"phone2\" class=\"phone\" type=\"text\" size=\"5\" onkeydown='return onlyNumber(event)' onkeyup='removeChar(event)'>\r\n");
      out.write("\t\t\t\t\t\t\t\t&nbsp;-&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"phone3\" class=\"phone\" type=\"text\" size=\"5\" onkeydown='return onlyNumber(event)' onkeyup='removeChar(event)'>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"thmo\">주소</th>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<span><input type=\"text\" id=\"sample6_address\" placeholder=\"주소\" size=\"46\" readonly=\"readonly\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t<span><input type=\"button\" onclick=\"sample6_execDaumPostcode()\" value=\"우편번호 찾기\"></span><br>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" id=\"sample6_detailAddress\" placeholder=\"상세주소\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" id=\"sample6_extraAddress\" placeholder=\"참고항목\" readonly=\"readonly\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th class=\"thmo\">배송 요청사항</th>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<select id=\"selbox\" name=\"selbox\" style=\"height:21.33px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"부재시 경비실에 맡겨주세요.\">부재시 경비실에 맡겨주세요.</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"집 앞에 놓아주세요.\">집 앞에 놓아주세요.</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"택배함에 넣어주세요.\">택배함에 넣어주세요.</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <option value=\"direct\">직접입력</option> -->\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"selfmessageinput\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"PList\">\r\n");
      out.write("\t\t\t\t<font  color=\"#5D5D5D\" size=\"5\" style=\"margin-left: 5%; font-weight:300;\">주문상품 정보</font><br>\r\n");
      out.write("\t\t\t\t<span><img src=\"");
      out.print(pathImg );
      out.write("\" style=\"width:100px; height:100px;\"></span>\r\n");
      out.write("\t\t\t\t<span>상품명:");
      out.print(buyList.getpName());
      out.write("</span>\r\n");
      out.write("\t\t\t\t<span>가격:");
      out.print(buyList.getpPrice());
      out.write("</span>\r\n");
      out.write("\t\t\t\t<span>수량:");
      out.print(buyList.getpCount());
      out.write("</span>\r\n");
      out.write("\t\t\t\t<span>합계:");
      out.print(buyList.getpPrice()*buyList.getpCount());
      out.write("</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"pay\">\r\n");
      out.write("\t\t\t\t<div id=\"payinfo1\">\r\n");
      out.write("\t\t\t\t\t<font  color=\"#5D5D5D\" size=\"5\" style=\"margin-left: 5%; font-weight:300;\">결제 정보</font>\r\n");
      out.write("\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t결제 수단 <br><br>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"javascript:void(0);\" id=\"aaa\" style=\" display: inline-block; width: 150px; height: 40px; text-decoration:none; text-align: center;\">\r\n");
      out.write("\t\t\t\t\t\t\t<font size=\"3\">신용카드</font>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"javascript:void(0);\" id=\"bbb\" style=\" display: inline-block; width: 150px; height: 40px; text-decoration:none; text-align: center;\">\r\n");
      out.write("\t\t\t\t\t\t\t<font size=\"3\">무통장입금</font>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"javascript:void(0);\"  id=\"ccc\" style=\" display: inline-block; width: 150px; height: 40px; text-decoration:none; text-align: center;\">\r\n");
      out.write("\t\t\t\t\t\t\t<font size=\"3\">실시간 계좌이체</font>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"javascript:void(0);\"  id=\"ddd\" style=\" display: inline-block; width: 150px; height: 40px; text-decoration:none; text-align: center;\">\r\n");
      out.write("\t\t\t\t\t\t\t<font size=\"3\">휴대폰결제</font>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"javascript:void(0);\"  id=\"eee\" style=\" display: inline-block; width: 150px; height: 40px; text-decoration:none; text-align: center;\">\r\n");
      out.write("\t\t\t\t\t\t\t<font size=\"3\">삼성페이</font>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<br><br>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div id=\"infoarea\" style=\"width:460px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t\t\t\t$(\"#aaa\").click(function() {\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"throw\").value = 'card';\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t$(\"#bbb\").click(function() {\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#infoarea\").hide();\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"throw\").value = 'vbank';\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t$(\"#ccc\").click(function() {\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#infoarea\").hide();\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"throw\").value = 'trans';\r\n");
      out.write("\t\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t$(\"#ddd\").click(function() {\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#infoarea\").hide();\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"throw\").value = 'phone';\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t$(\"#eee\").click(function() {\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#infoarea\").hide();\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"throw\").value = 'samsung';\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t<div id=\"payinfo2\">\r\n");
      out.write("\t\t\t\t\t<font  color=\"#5D5D5D\" size=\"5\" style=\"margin-left: 5%; font-weight:300;\">결제 금액</font>\r\n");
      out.write("\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"payall\" style=\"border: 1px solid; width: 500px; height: 300px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<font>상품 금액</font>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
int a = buyList.getpPrice()*buyList.getpCount();
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.print(a);
      out.write("원\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<font>배송비</font>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
int b = 5000; 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.print(b );
      out.write("원\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"border: 1px solid; width: 500px; height: 100px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<font>최종 결제금액 </font>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
      out.print(a+b);
      out.write("원\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"paysubmit\" type=\"button\" value=\"결제하기\" onclick=\"paygo()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- 결제 방법 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"throw\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- 상품명 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"throw2\" value=");
      out.print(buyList.getpName());
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- 결제금액 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"throw3\" value=");
      out.print(a+b);
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- 수량 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" id=\"throw4\" value=");
      out.print(buyList.getpCount());
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\t<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
