/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2019-10-25 08:28:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import board.model.vo.*;
import java.util.*;

public final class PListUpdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("board.model.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
 
	request.setCharacterEncoding("UTF-8");
	String name = request.getParameter("pName");
	String price = request.getParameter("pPrice");
	String count = request.getParameter("pCount");
	String add = request.getParameter("add1");
	String day = request.getParameter("pDay");
	String period = request.getParameter("pPeriod");
	String sell = request.getParameter("sell_price");
	String sums = request.getParameter("sum");

	String img = request.getParameter("pathImg");
	
	String notice = request.getParameter("pNotice");
	String delivery = request.getParameter("pDelivery");


      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Noto+Serif+KR:200,300&display=swap&subset=korean\" rel=\"stylesheet\">\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("<title>상품 등록페이지</title>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t.mainInfo{\r\n");
      out.write("\t   \r\n");
      out.write("\t\tborder: 1px solid;\r\n");
      out.write("\t\tborder-color: #ddd #ddd #CACACA;\r\n");
      out.write("\t\twidth: 935px;\r\n");
      out.write("    \theight: 461px;\r\n");
      out.write("    \tmargin-left:auto;\r\n");
      out.write("        margin-right:auto;\r\n");
      out.write("        margin-top:50px;\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.mainArea{\r\n");
      out.write("\t\twidth: 935px;\r\n");
      out.write("\r\n");
      out.write("    \tborder: 1px solid;\r\n");
      out.write("    \tborder-color: #ddd #ddd #CACACA;\r\n");
      out.write("    \tmargin-left:auto;\r\n");
      out.write("        margin-right:auto;\r\n");
      out.write("        margin-top:10px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.btnArea{\r\n");
      out.write("\t\twidth: 100px;\r\n");
      out.write("\t\tmargin-left: auto;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.info {\r\n");
      out.write("    display: block;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    height: 13px;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    font-size: 15px;\r\n");
      out.write("    line-height: 13px;\r\n");
      out.write("    color: #999;\r\n");
      out.write("    white-space: nowrap;\r\n");
      out.write("    letter-spacing: -1px;\r\n");
      out.write("    text-overflow: ellipsis;\r\n");
      out.write("    white-space: nowrap;\r\n");
      out.write("    word-wrap: normal;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\t.title {\r\n");
      out.write("\t    min-height: 86px;\r\n");
      out.write("\t    margin: 9px 0 26px 0;\r\n");
      out.write("\t    font-size: 21px;\r\n");
      out.write("\t    line-height: 29px;\r\n");
      out.write("\t    color: #333;\r\n");
      out.write("\t    font-weight: bold;\r\n");
      out.write("\t    letter-spacing: -1px;\r\n");
      out.write("\t    word-wrap: break-word;\r\n");
      out.write("\t    word-break: break-all;\r\n");
      out.write("\t}\r\n");
      out.write("\t.dearArea {\r\n");
      out.write("\t\tdisplay:inline;float:left; width:466px; border: 0px solid;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t.layer{\r\n");
      out.write("\t\tmargin-top: auto; \r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.navList{\r\n");
      out.write("\t\tpadding: 0;\r\n");
      out.write("\t\tmargin: 0;\r\n");
      out.write("\t\tlist-style: none;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.tab ul {\r\n");
      out.write("\t\tdisplay: flex;\r\n");
      out.write("\t\theight: 60px;\r\n");
      out.write("\t\tborder-bottom: 1px solid #5da62b;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.tab ul li {\r\n");
      out.write("\t\tflex:1; \r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.tab ul li:first-child a {\r\n");
      out.write("\t\tborder-left: 1px solid #ddd; \r\n");
      out.write("\t}\r\n");
      out.write("\t.tab ul li a {\r\n");
      out.write("\t\tdisplay: block;\r\n");
      out.write("\t\theight: 59px;\r\n");
      out.write("\t\tborder: 1px solid #ddd; \r\n");
      out.write("\t\tborder-left: none;\r\n");
      out.write("\t\tborder-bottom: none;\r\n");
      out.write("\t\tfont-size: 14px;\r\n");
      out.write("\t\tcolor: 505050;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tline-height: 59px; \r\n");
      out.write("\t\ttext-decoration: none;\r\n");
      out.write("\t}\r\n");
      out.write("\t.tab ul li a.on:hover{\r\n");
      out.write("\t\tposition: relative;\r\n");
      out.write("\t\theight: 58px;\r\n");
      out.write("\t\tborder-color: #5da62b;\r\n");
      out.write("\t\tborder-top-width: 2px;\r\n");
      out.write("\t\tline-height: 57px;\r\n");
      out.write("\t\tborder-bottom: 1px solid #fff;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t#imgArea{\r\n");
      out.write("\t\tdisplay:inline;\r\n");
      out.write("\t\tfloat:left;\r\n");
      out.write("\t\twidth:465px; \r\n");
      out.write("\t\theight:460px;\r\n");
      out.write("\t\tborder: 1px solid; \r\n");
      out.write("\t\tborder-color: #ddd #ddd #CACACA;\r\n");
      out.write("\t}\r\n");
      out.write("\t#imgArea:hover {\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("\t}\r\n");
      out.write("\t#imgs1:hover {\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("\t}\r\n");
      out.write("\t#imgs2:hover {\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("\t}\r\n");
      out.write("\t#imgs3:hover {\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("\t}\r\n");
      out.write("\t#imgs4:hover {\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("\t}\r\n");
      out.write("\t#imgs5:hover {\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("\t}\r\n");
      out.write("\ta.top {\r\n");
      out.write("\t  position: fixed;\r\n");
      out.write("\t  left: 50%;\r\n");
      out.write("\t  bottom: 50px;\r\n");
      out.write("\t  display: none;\r\n");
      out.write("\t}\r\n");
      out.write("\t \r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t$( window ).scroll( function() {\r\n");
      out.write("\t\tif ( $( this ).scrollTop() > 200 ) {\r\n");
      out.write("\t\t\t$( '.top' ).fadeIn();\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$( '.top' ).fadeOut();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t} );\r\n");
      out.write("\t\r\n");
      out.write("\t$( '.top' ).click( function() {\r\n");
      out.write("\t\t$( 'html, body' ).animate( { scrollTop : 0 }, 400 );\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t} );\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t\t\t$(function() {\r\n");
      out.write("\t\t\t\tif(false){\r\n");
      out.write("\t\t\t\t\talert(\"비정상적인 접근입니다! (허가되지 않은 사용자)\\n로그인후 이용해주세요!\");\r\n");
      out.write("\t\t\t\t\twindow.close();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#resetAlls\").click(function() {\r\n");
      out.write("\t\t\t\t\t$('#pInput1').val('');\r\n");
      out.write("\t\t\t\t\t$('#pInput2').val('');\r\n");
      out.write("\t\t\t\t\t$('#pInput3').val('');\r\n");
      out.write("\t\t\t\t\t$('#add1').val('');\r\n");
      out.write("\t\t\t\t\t$('#pInput5').val('');\r\n");
      out.write("\t\t\t\t\t$('#pInput6').val('');\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#fileArea\").hide();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#imgArea\").click(function() {\r\n");
      out.write("\t\t\t\t\t$(\"#mainImg\").click();\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#imgs1\").click(function() {\r\n");
      out.write("\t\t\t\t\t$(\"#ImgList1\").click();\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$(\"#imgs2\").click(function() {\r\n");
      out.write("\t\t\t\t\t$(\"#ImgList2\").click();\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$(\"#imgs3\").click(function() {\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\"#ImgList3\").click();\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$(\"#imgs4\").click(function() {\r\n");
      out.write("\t\t\t\t\t$(\"#ImgList4\").click();\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$(\"#imgs5\").click(function() {\r\n");
      out.write("\t\t\t\t\t$(\"#ImgList5\").click();\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tindex = 1;\r\n");
      out.write("\t\t\t\t// 추가버튼 클릭시 작동\r\n");
      out.write("\t\t\t\t$(\"#addTable\").click(function(){\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$addDiv = $(\"#ImgsTextArea\");\r\n");
      out.write("\t\t\t\t\tif(index <6){\r\n");
      out.write("\t\t\t\t\t\t/* var $div = $(\"<div>\").attr(\"id\", \"imgss\"+index); */\r\n");
      out.write("\t\t\t\t\t\tvar $img = $(\"<img>\").attr(\"id\",\"imgs\"+index).css({\"width\":\"751px\",\"height\":\"600px\",\"margin-left\":\"3%\",\"margin-right\":\"3%\"});\r\n");
      out.write("\t\t\t\t\t\tvar $input = $(\"<input>\").attr({\"type\":\"file\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"id\":\"ImgList\"+index,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"multiple\":\"multiple\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"name\":\"pImg\"+index,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"onchange\":\"LoadImg(this,\"+(1+index)+\")\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tvar $textarea =$(\"<textarea>\").attr({\"rows\":\"15\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t \"cols\":\"104\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t \"id\":\"textList\"+index,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t \"name\":\"pText\"+index\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t}).css({\"margin-left\":\"3%\",\"margin-right\":\"3%\", \"width\":\"745px\"});\r\n");
      out.write("\t\t\t\t\t\t$img.click(function(){\r\n");
      out.write("\t\t\t\t\t\t\t$input.click();\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t$addDiv.append($img);\r\n");
      out.write("\t\t\t\t\t\t$addDiv.append($textarea);\r\n");
      out.write("\t\t\t\t\t\t$addDiv.append($input);\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tindex = index +1;\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write(" \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfunction LoadImg(value, num) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tif(value.files[0]!=undefined) {\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t// value는 함수를 발동시킨 객체(file타입 input태그)이고\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t// value.files[0]은 input태그로 파일을 선택 했으면 undefined가 아니고 선택 안했으면 undefined다.\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tvar reader = new FileReader();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\treader.onload = function(e) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tswitch (num) {\r\n");
      out.write("\t\t\t\t\t\tcase 1:\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#titleImg\").attr(\"src\",e.target.result);\r\n");
      out.write("\t\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t\tcase 2:\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#imgs1\").attr(\"src\",e.target.result);\r\n");
      out.write("\t\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t\tcase 3:\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#imgs2\").attr(\"src\",e.target.result);\r\n");
      out.write("\t\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t\tcase 4:\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#imgs3\").attr(\"src\",e.target.result);\r\n");
      out.write("\t\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t\tcase 5:\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#imgs4\").attr(\"src\",e.target.result);\r\n");
      out.write("\t\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t\tcase 6:\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#imgs5\").attr(\"src\",e.target.result);\r\n");
      out.write("\t\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\treader.readAsDataURL(value.files[0]);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t  var idx;\r\n");
      out.write("\t\t\t  var obj_table;\r\n");
      out.write("\t\t\t  function my_init() {\r\n");
      out.write("\t\t\t    idx = 0;\r\n");
      out.write("\t\t\t    obj_table = document.all.Imgss.cloneNode(true);\r\n");
      out.write("\t\t\t  }\r\n");
      out.write("\t\t\t  function add_table() {\r\n");
      out.write("\t\t\t    if (idx<4) {  //등록가능갯수 5개로 제한\r\n");
      out.write("\t\t\t        idx++;\r\n");
      out.write("\t\t\t        eval(\"document.all.Imgss\"+(idx>1?idx-1:\"\")).insertAdjacentHTML(\"afterEnd\",obj_table.outerHTML.replace(\"Imgss\",\"Imgss\"+idx));\r\n");
      out.write("\t\t\t        \r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t\t  }\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t        function openChild1() {\r\n");
      out.write("\t            // window.name = \"부모창 이름\"; \r\n");
      out.write("\t            window.name = \"PListUpdate.jsp\";\r\n");
      out.write("\t            // window.open(\"open할 window\", \"자식창 이름\", \"팝업창 옵션\");\r\n");
      out.write("\t            window.open(\"PopupUpdate.jsp\",\r\n");
      out.write("\t                    \"childForm\", \"margin-left=auto margin-right=auto width=660, height=280, location = no, resizable = no, scrollbars = no\");    \r\n");
      out.write("\t        }\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<form action = \"");
      out.print(request.getContextPath());
      out.write("/insert.bo\" method=\"post\" encType=\"multipart/form-data\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"layer\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div class=\"mainInfo\">\r\n");
      out.write("\t\t\t\t<div id=\"imgArea\">\r\n");
      out.write("\t\t\t\t\t<img src=");
      out.print(img );
      out.write(" id=\"titleImg\" width=\"465px\" height=\"460px\" name=\"pMainimg\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t<br><br><br><br>\r\n");
      out.write("\t\t\t\t<div class=\"dearArea\">\r\n");
      out.write("\t\t\t\t\t<div id=\"List\">\r\n");
      out.write("\t   \t\t\t\t\t\t<font size=\"5em\" color=\"black\" style=\"font-family: Noto Serif KR\">판매 물품명 : </font> \r\n");
      out.write("\t   \t\t\t\t\t\t<input type=\"text\" name=\"pName\" style=\" width:305px; height:30px; font-size:20px; color:red; border: 0px;\" id=\"pInput1\" readonly=\"readonly\" value=");
      out.print(name );
      out.write(">\r\n");
      out.write("\t   \t\t\t\t\t\t <font size=\"5em\" color=\"black\" style=\"font-family: Noto Serif KR\"\">가격 : </font>\r\n");
      out.write("\t   \t\t\t\t\t\t <input type=\"text\" name=\"pPrice\" style=\" width:150px; text-align:right; font-size:20px; color:red; border: 0px;\" id=\"pInput2\" readonly=\"readonly\" value=");
      out.print(price );
      out.write(">원<br>\r\n");
      out.write("\t   \t\t\t\t\t\t <font size=\"4em\" color=\"black\" style=\"font-family: Noto Serif KR\"\">재고량 : </font> \r\n");
      out.write("\t   \t\t\t\t\t\t <input type=\"text\" name=\"pCount\" style=\" width:150px; text-align:right; font-size:18px; color:black; border: 0px;\" id=\"pInput3\" readonly=\"readonly\" value=");
      out.print(count );
      out.write(">개<br>\r\n");
      out.write("\t   \t\t\t\t\t\t <font size=\"4em\" color=\"black\" style=\"font-family: Noto Serif KR\"\"> 원산지 : </font>\r\n");
      out.write("\t\t\t\t\t\t\t <input type=\"text\" size=\"30\" id=\"add1\" name=\"add1\" style=\"font-size:18px; color:black; border: 0px;\" readonly=\"readonly\" value=\"");
      out.print(add);
      out.write("\"><br>\r\n");
      out.write("\t   \t\t\t\t\t\t <font size=\"3em\" color=\"black\" style=\"font-family: Noto Serif KR\">생산일자 : </font> \r\n");
      out.write("\t   \t\t\t\t\t\t <input type=\"date\" id=\"pInput5\" name=\"pDay\" value=\"");
      out.print(day);
      out.write("\" style=\"font-size:15px; color:black; border: 0px;\" readonly=\"readonly\"><br>\r\n");
      out.write("\t   \t\t\t\t\t\t <font size=\"3em\" color=\"black\" style=\"font-family: Noto Serif KR\">유통기한 : </font> \r\n");
      out.write("\t   \t\t\t\t\t\t <input type=\"date\" id=\"pInput6\" name=\"pPeriod\" value=\"");
      out.print(period );
      out.write("\" style=\"font-size:15px; color:black; border: 0px;\" readonly=\"readonly\">\r\n");
      out.write(" \r\n");
      out.write("   \t\t\t\t\t<div>\r\n");
      out.write("   \t\t\t\t\t\t<button type=\"button\" id=\"resetAlls\" style=\"margin-left: 100px\">모든 내용 지우기</button>\r\n");
      out.write("\t   \t\t\t\t\t<input type=\"button\" value=\"기본정보 입력하기\" onclick=\"openChild1()\" style=\"margin-left: 40px\">\r\n");
      out.write("   \t\t\t\t\t</div>\r\n");
      out.write("   \t\t\t\t\r\n");
      out.write("   \t\t\t\t\t<br><br><br>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div style=\"width: 935px; margin-left: auto; margin-right: auto;\">\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"mainArea\">\r\n");
      out.write("\t\t\t<nav class=\"tab\">\r\n");
      out.write("\t\t\t\t<ul class=\"navList\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#sList1\" class=\"on\">1. 상품정보</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#sList2\" class=\"on\">2. 상품 유의사항</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#sList3\" class=\"on\">3. 배송 유의사항</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#sList4\" class=\"on\">4. 등록 및 승인요청</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"sList1\" style=\"margin-left: auto; margin-right: auto; margin-top: 20px; border: 1px solid; border-color: #ddd #ddd #CACACA;\">\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!-- <div id=\"vedioArea\" style=\"margin-left: auto; margin-right:auto;  width: 750px; height: 550px; border: 1px solid red;\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"file\" value=\"동영상 업로드\" name=\"pVideo\">\r\n");
      out.write("\t\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div id=\"ImgsTextArea\" style=\"margin-left: auto; margin-right:auto; width: 800px; height: 100%;\">\r\n");
      out.write("\t\t\t\t\t\t<div id =\"Imgss\">\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t     \t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div style=\"margin-left: 45%; margin-right: 45%\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"addTable\" type=\"button\" value=\"내용 추가\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"sList2\" style=\"margin-left: auto; margin-right: auto; margin-top: 20px; border: 1px solid; border-color: #ddd #ddd #CACACA;\">\r\n");
      out.write("\t\t\t\t상품 유의사항 작성\r\n");
      out.write("\t\t\t\t<textarea name=\"pNotice\" rows=\"10\" cols=\"130\" style=\"width: 927px; height: 250px\">");
      out.print(notice);
      out.write("</textarea>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"sList3\" style=\"margin-left: auto; margin-right: auto; margin-top: 20px; border: 1px solid; border-color: #ddd #ddd #CACACA;\">\r\n");
      out.write("\t\t\t\t배송 유의사항 작성\r\n");
      out.write("\t\t\t\t<textarea name=\"pDelivery\" rows=\"10\" cols=\"130\" style=\"width: 927px; height: 250px\">");
      out.print(delivery);
      out.write("</textarea>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"sList4\" style=\"margin-left: auto; margin-right: auto; margin-top: 20px; border: 1px solid; border-color: #ddd #ddd #CACACA;\">\r\n");
      out.write("\t\t\t\t<div style=\"width: 600px; height: 100px; margin-left: 45%; margin-right: 45%; margin-top: 5%\">\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"게시글 등록요청\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<a href=\"#\" class=\"top\" style=\"margin-left: 40%\"><img src=\"../images/upup.png\"></a>\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"fileArea\">\r\n");
      out.write("\t\t\t<input type=\"file\" id=\"mainImg\" multiple=\"multiple\" name=\"mainImg\" onchange=\"LoadImg(this,1)\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\t\t<br><br><br><br><br>\r\n");
      out.write("\t\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
