/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2019-10-25 08:27:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import board.model.vo.*;
import java.util.*;

public final class PListView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("board.model.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");

    	Board b = (Board)request.getAttribute("board");
    	ArrayList<Attachment> fileList = (ArrayList<Attachment>)request.getAttribute("fileList"); 
    	
    	Attachment titleImg = fileList.get(0);	// 대표사진(fileLevel=0)
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("<title>상품 정보페이지</title>\r\n");
      out.write("<style>\r\n");
      out.write("\t.mainInfo{\r\n");
      out.write("\t   \r\n");
      out.write("\t\tborder: 1px solid;\r\n");
      out.write("\t\tborder-color: #ddd #ddd #CACACA;\r\n");
      out.write("\t\twidth: 935px;\r\n");
      out.write("    \theight: 461px;\r\n");
      out.write("    \tmargin-left:auto;\r\n");
      out.write("        margin-right:auto;\r\n");
      out.write("        margin-top:50px;\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.mainArea{\r\n");
      out.write("\t\twidth: 935px;\r\n");
      out.write("\r\n");
      out.write("    \tborder: 1px solid;\r\n");
      out.write("    \tborder-color: #ddd #ddd #CACACA;\r\n");
      out.write("    \tmargin-left:auto;\r\n");
      out.write("        margin-right:auto;\r\n");
      out.write("        margin-top:10px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.btnArea{\r\n");
      out.write("\t\twidth: 100px;\r\n");
      out.write("\t\tmargin-left: auto;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.info {\r\n");
      out.write("    display: block;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    height: 13px;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    font-size: 15px;\r\n");
      out.write("    line-height: 13px;\r\n");
      out.write("    color: #999;\r\n");
      out.write("    white-space: nowrap;\r\n");
      out.write("    letter-spacing: -1px;\r\n");
      out.write("    text-overflow: ellipsis;\r\n");
      out.write("    white-space: nowrap;\r\n");
      out.write("    word-wrap: normal;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\t.title {\r\n");
      out.write("\t    min-height: 86px;\r\n");
      out.write("\t    margin: 9px 0 26px 0;\r\n");
      out.write("\t    font-size: 21px;\r\n");
      out.write("\t    line-height: 29px;\r\n");
      out.write("\t    color: #333;\r\n");
      out.write("\t    font-weight: bold;\r\n");
      out.write("\t    letter-spacing: -1px;\r\n");
      out.write("\t    word-wrap: break-word;\r\n");
      out.write("\t    word-break: break-all;\r\n");
      out.write("\t}\r\n");
      out.write("\t.dearArea {\r\n");
      out.write("\t\tdisplay:inline;float:left; width:466px; border: 1px solid; border-color: #ddd #ddd #CACACA;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t.layer{\r\n");
      out.write("\t\tmargin-top: auto; \r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.navList{\r\n");
      out.write("\t\tpadding: 0;\r\n");
      out.write("\t\tmargin: 0;\r\n");
      out.write("\t\tlist-style: none;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.tab ul {\r\n");
      out.write("\t\tdisplay: flex;\r\n");
      out.write("\t\theight: 60px;\r\n");
      out.write("\t\tborder-bottom: 1px solid #5da62b;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.tab ul li {\r\n");
      out.write("\t\tflex:1; \r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.tab ul li:first-child a {\r\n");
      out.write("\t\tborder-left: 1px solid #ddd; \r\n");
      out.write("\t}\r\n");
      out.write("\t.tab ul li a {\r\n");
      out.write("\t\tdisplay: block;\r\n");
      out.write("\t\theight: 59px;\r\n");
      out.write("\t\tborder: 1px solid #ddd; \r\n");
      out.write("\t\tborder-left: none;\r\n");
      out.write("\t\tborder-bottom: none;\r\n");
      out.write("\t\tfont-size: 14px;\r\n");
      out.write("\t\tcolor: 505050;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tline-height: 59px; \r\n");
      out.write("\t\ttext-decoration: none;\r\n");
      out.write("\t}\r\n");
      out.write("\t.tab ul li a.on:hover{\r\n");
      out.write("\t\tposition: relative;\r\n");
      out.write("\t\theight: 58px;\r\n");
      out.write("\t\tborder-color: #5da62b;\r\n");
      out.write("\t\tborder-top-width: 2px;\r\n");
      out.write("\t\tline-height: 57px;\r\n");
      out.write("\t\tborder-bottom: 1px solid #fff;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t#imgArea{\r\n");
      out.write("\t\tdisplay:inline;\r\n");
      out.write("\t\tfloat:left;\r\n");
      out.write("\t\twidth:465px; \r\n");
      out.write("\t\theight:460px;\r\n");
      out.write("\t\tborder: 1px solid; \r\n");
      out.write("\t\tborder-color: #ddd #ddd #CACACA;\r\n");
      out.write("\t}\r\n");
      out.write("\t#imgArea:hover {\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("\t}\r\n");
      out.write("\t \r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<!-- 수량 증가감소 합계 스크립트 -->\r\n");
      out.write("\t\t\t\t\t<script language=\"JavaScript\">\r\n");
      out.write("\t\t\t\t\t\tvar sell_price;\r\n");
      out.write("\t\t\t\t\t\tvar amount;\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tfunction init () {\r\n");
      out.write("\t\t\t\t\t\t\tsell_price = document.form.sell_price.value;\r\n");
      out.write("\t\t\t\t\t\t\tamount = document.form.amount.value;\r\n");
      out.write("\t\t\t\t\t\t\tdocument.form.sum.value = sell_price;\r\n");
      out.write("\t\t\t\t\t\t\tchange();\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tfunction add () {\r\n");
      out.write("\t\t\t\t\t\t\thm = document.form.amount;\r\n");
      out.write("\t\t\t\t\t\t\tsum = document.form.sum;\r\n");
      out.write("\t\t\t\t\t\t\thm.value ++ ;\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\tsum.value = parseInt(hm.value) * sell_price;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tfunction del () {\r\n");
      out.write("\t\t\t\t\t\t\thm = document.form.amount;\r\n");
      out.write("\t\t\t\t\t\t\tsum = document.form.sum;\r\n");
      out.write("\t\t\t\t\t\t\t\tif (hm.value > 1) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\thm.value -- ;\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsum.value = parseInt(hm.value) * sell_price;\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tfunction change () {\r\n");
      out.write("\t\t\t\t\t\t\thm = document.form.amount;\r\n");
      out.write("\t\t\t\t\t\t\tsum = document.form.sum;\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\tif (hm.value < 0) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\thm.value = 0;\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tsum.value = parseInt(hm.value) * sell_price;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body onload=\"init()\">\r\n");
      out.write("<form name=\"form\" method=\"post\">\r\n");
      out.write("\t\t<div class=\"layer\">\r\n");
      out.write("\t\t\t<div class=\"mainInfo\">\r\n");
      out.write("\t\t\t\t<div id=\"imgArea\">\r\n");
      out.write("\t\t\t\t\t<img src=\"");
      out.print(request.getContextPath() );
      out.write("/uploadFiles/");
      out.print(titleImg.getChangeName() );
      out.write("\" id=\"titleImg\" width=\"465px\" height=\"460px\" name=\"mainImg\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"pid\" name=\"pid\" value=\"");
      out.print(b.getpId() );
      out.write("\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"sid\" name=\"sid\" value=\"");
      out.print(b.getsId() );
      out.write("\">\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"pathImg\" name=\"pathImg\" value=\"");
      out.print(request.getContextPath() );
      out.write("/uploadFiles/");
      out.print(titleImg.getChangeName() );
      out.write("\">\r\n");
      out.write("\t\t\t<br><br><br><br>\r\n");
      out.write("\t\t\t\t<div class=\"dearArea\">\r\n");
      out.write("\t\t\t\t\t<div id=\"List\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t   \t\t\t\t\t\t<font size=\"5em\" color=\"green\" style=\"font-weight: bold;\">판매 물품명 : </font> <input type=\"text\" name=\"pName\" style=\"font-size:20px; color:red; border: 0px;\" id=\"pInput1\" readonly=\"readonly\" value=");
      out.print(b.getpName() );
      out.write("> <br>\r\n");
      out.write("\t   \t\t\t\t\t\t \t\t\r\n");
      out.write("\t   \t\t\t\t\t\t <font size=\"5em\" color=\"green\" style=\"font-weight: bold;\">가격 : </font> <input type=\"text\" name=\"pPrice\" style=\"font-size:20px; color:red; border: 0px;\" id=\"pInput2\" readonly=\"readonly\" value=");
      out.print( b.getpPrice() );
      out.write("><br>\r\n");
      out.write("\t   \t\t\t\t\t\t \t\t\r\n");
      out.write("\t   \t\t\t\t\t\t <font size=\"4em\" color=\"green\" style=\"font-weight: bold;\">재고량 : </font> <input type=\"text\" name=\"pCount\" style=\"font-size:18px; color:red; border: 0px;\" id=\"pInput3\" readonly=\"readonly\" value=");
      out.print(b.getpCount() );
      out.write("><br>\r\n");
      out.write("\t \t\t\t\t\t\t\t\r\n");
      out.write("\t   \t\t\t\t\t\t<font size=\"4em\" color=\"green\" style=\"font-weight: bold;\"> 원산지 : </font>\r\n");
      out.write("\t   \t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" size=\"30\" id=\"add1\" name=\"add1\" style=\"font-size:18px; color:red; border: 0px;\" readonly=\"readonly\" value=\"");
      out.print(b.getpAddress() );
      out.write("\"><br>\r\n");
      out.write("\t   \t\t\t\t\t\t \t\t\r\n");
      out.write("\t   \t\t\t\t\t\t <font size=\"3em\" color=\"green\" style=\"font-weight: bold;\">생산일자 : </font> <input type=\"text\" name=\"pDay\" style=\"font-size:15px; color:red; border: 0px;\" id=\"pInput5\" readonly=\"readonly\" value=\"");
      out.print(b.getpDay() );
      out.write("\"><br>\r\n");
      out.write("\t   \t\t\t\t\t\t \t\t\r\n");
      out.write("\t   \t\t\t\t\t\t <font size=\"3em\" color=\"green\" style=\"font-weight: bold;\">유통기한 : </font> <input type=\"text\" name=\"pPeriod\" style=\"font-size:15px; color:red; border: 0px;\" id=\"pInput6\" readonly=\"readonly\" value=\"");
      out.print(b.getpPeriod() );
      out.write("\"><br><br>\r\n");
      out.write("\t   \t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t \r\n");
      out.write("\t   \t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t수량 : <input type=\"hidden\" name=\"sell_price\" value=");
      out.print(b.getpPrice());
      out.write(">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"amount\" value=\"1\" size=\"3\" onchange=\"change();\" readonly=\"readonly\" >\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\" - \" onclick=\"del();\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\" + \" onclick=\"add();\"><br>\r\n");
      out.write("\t\t\t\t\t금액 : <input type=\"text\" name=\"sum\" size=\"11\" readonly=\"readonly\">원\r\n");
      out.write("\t   \t\t\t\t\r\n");
      out.write("\t   \t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div style=\"margin-left: 30%; margin-right: 30%; margin-top: 10%\">\r\n");
      out.write("\t\t\t\t\t\t<span><button id=\"basket\">장바구니 담기</button></span>\r\n");
      out.write("\t\t\t\t\t\t<span><button id=\"buy\">바로 구매</button></span>\r\n");
      out.write("\t\t\t\t\t\t<button id=\"modify\">수정하기</button>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t$(\"#buy\").click(function () {\r\n");
      out.write("\t\t\t\t\t\t       $(\"form\").attr(\"action\", \"");
      out.print(request.getContextPath());
      out.write("/plist.bo\");\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t$(\"#basket\").click(function () {\r\n");
      out.write("\t\t\t\t\t\t       $(\"form\").attr(\"action\", \"");
      out.print(request.getContextPath());
      out.write("/basket.bo\");\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t$(\"#modify\").click(function () {\r\n");
      out.write("\t\t\t\t\t\t       $(\"form\").attr(\"action\", \"");
      out.print(request.getContextPath());
      out.write("/view/PListUpdate.jsp\");\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</script>\r\n");
      out.write("   \t\t\t\t\t\t \r\n");
      out.write("   \t\t\t\t\t<br><br><br>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<div style=\"width: 935px; margin-left: auto; margin-right: auto;\">\r\n");
      out.write("\t\t\t<hr>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"mainArea\">\r\n");
      out.write("\t\t\t<nav class=\"tab\">\r\n");
      out.write("\t\t\t\t<ul class=\"navList\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#sList1\" class=\"on\">1. 상품정보</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#sList2\" class=\"on\">2. 상품 유의사항</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#sList3\" class=\"on\">3. 배송 유의사항</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#sList4\" class=\"on\">4. 구매자 리뷰</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"sList1\" style=\"margin-left: auto; margin-right: auto; margin-top: 20px; border: 1px solid; border-color: #ddd #ddd #CACACA;\">\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div id=\"ImgsTextArea\" style=\"margin-left: 10%; margin-right:10%; width: 800px; height: 100%;\">\r\n");
      out.write("\t\t\t\t\t\t<div id =\"Imgss\" style=\"margin-left: auto; margin-right:auto; width: 800px; height: 100%;\">\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t");

								String[] sarray =  {"",b.getpText1(),b.getpText2(),b.getpText3(),b.getpText4(),b.getpText5()};
							
							for(int i=1;i<fileList.size();i++) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img  id=\"imgView1\" src=\"");
      out.print(request.getContextPath() );
      out.write("/uploadFiles/");
      out.print(fileList.get(i).getChangeName() );
      out.write("\" style=\"width:750px; height: 600px; margin-left: 3% margin-right:3%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<textarea id=\"textView1\" style=\" margin-right: 10%; width: 744px; height: 200px; resize: none;\">");
      out.print(sarray[i] );
      out.write("</textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</tr> \r\n");
      out.write("\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"sList2\" style=\"margin-left: auto; margin-right: auto; margin-top: 20px; border: 1px solid; border-color: #ddd #ddd #CACACA;\">\r\n");
      out.write("\t\t\t\t상품 유의사항 입니다.\r\n");
      out.write("\t\t\t\t<textarea name=\"pNotice\" id=\"notice\" rows=\"10\" cols=\"130\" style=\"width: 927px; height: 250px; border: 0px solid;\">");
      out.print(b.getpNotice() );
      out.write("</textarea>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"sList3\" style=\"margin-left: auto; margin-right: auto; margin-top: 20px; border: 1px solid; border-color: #ddd #ddd #CACACA;\">\r\n");
      out.write("\t\t\t\t배송 유의사항 입니다.\r\n");
      out.write("\t\t\t\t<textarea name=\"pDelivery\" id=\"delivery\" rows=\"10\" cols=\"130\" style=\"width: 927px; height: 250px\">");
      out.print(b.getpDelivery() );
      out.write("</textarea>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"sList4\" style=\"margin-left: auto; margin-right: auto; margin-top: 20px; border: 1px solid; border-color: #ddd #ddd #CACACA;\">\r\n");
      out.write("\t\t\t\t구매자 리뷰 입니다.\r\n");
      out.write("\t\t\t\t<div style=\"width: 600px; height: 100px;\" >\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
